version: 0.2

env:
  variables:
    INDEX_FUNC_NAME: "index-photos"
    SEARCH_FUNC_NAME: "search-photos"

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "=== INSTALL PHASE ==="
      - yum update -y
      - yum install -y zip

  build:
    commands:
      - echo "=== BUILD PHASE ==="
      - pwd
      - ls -l
      - cd photo-search-backend/index-photos
      - zip -r ../../index-photos.zip .
      - cd ../search-photos
      - zip -r ../../search-photos.zip .
      - cd ../../
      - ls -l

  post_build:
    commands:
      - echo "=== POST_BUILD PHASE ==="
      - echo "INDEX_FUNC_NAME=$INDEX_FUNC_NAME"
      - echo "SEARCH_FUNC_NAME=$SEARCH_FUNC_NAME"
      - aws lambda update-function-code --function-name "$INDEX_FUNC_NAME" --zip-file fileb://index-photos.zip
      - aws lambda update-function-code --function-name "$SEARCH_FUNC_NAME" --zip-file fileb://search-photos.zip
      - echo "Lambda updates complete."

