version: 0.2

env:
  variables:
    INDEX_FUNC_NAME: index-photos
    SEARCH_FUNC_NAME: search-photos

phases:
  install:
    commands:
      - echo "Installing zip (if needed)"
      - yum update -y
      - yum install -y zip

  build:
    commands:
      - echo "Zipping Lambda functions"
      - cd photo-search-backend/index-photos
      - zip -r ../../index-photos.zip .
      - cd ../search-photos
      - zip -r ../../search-photos.zip .
      - cd ../../

  post_build:
    commands:
      - echo "Updating Lambda functions"
      - aws lambda update-function-code --function-name "$INDEX_FUNC_NAME" --zip-file fileb://index-photos.zip
      - aws lambda update-function-code --function-name "$SEARCH_FUNC_NAME" --zip-file fileb://search-photos.zip

