version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Install phase - nothing special to install"

  build:
    commands:
      - echo "Build phase - zipping backend Lambda functions"
      - pwd
      - ls
      # Zip index-photos Lambda
      - cd photo-search-backend/index-photos
      - zip -r ../../index-photos.zip .
      # Zip search-photos Lambda
      - cd ../search-photos
      - zip -r ../../search-photos.zip .
      # Go back to repo root and list the zips
      - cd ../..
      - ls -l

artifacts:
  files:
    - index-photos.zip
    - search-photos.zip


