AWSTemplateFormatVersion: '2010-09-09'
Description: Photo search app - minimal stack for Assignment 3. Creates S3 buckets
  (frontend + photos), two Lambdas, and an API Gateway with /photos (PUT) and /search (GET) endpoints.

Parameters:
  FrontendBucketName:
    Type: String
    Description: Name for the frontend S3 bucket
  PhotosBucketName:
    Type: String
    Description: Name for the photos S3 bucket
  IndexFunctionName:
    Type: String
    Default: index-photos
    Description: Lambda name for indexing uploaded photos
  SearchFunctionName:
    Type: String
    Default: search-photos
    Description: Lambda name for searching photos

Resources:
  # ---------------- S3 buckets ----------------
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref FrontendBucketName

  PhotosBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref PhotosBucketName

  # ---------------- IAM role for Lambdas ----------------
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: photo-search-lambda-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: PhotoSearchS3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:ListBucket
                Resource:
                  - !Sub arn:aws:s3:::${PhotosBucketName}
                  - !Sub arn:aws:s3:::${PhotosBucketName}/*

  # ---------------- Lambda functions ----------------
  IndexFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref IndexFunctionName
      Runtime: python3.11
      Handler: lambda_function.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 30
      MemorySize: 256
      Code:
        S3Bucket: !Ref PhotosBucketName
        S3Key: lambda/index-photos.zip
      Environment:
        Variables:
          PHOTOS_BUCKET: !Ref PhotosBucketName

  SearchFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref SearchFunctionName
      Runtime: python3.11
      Handler: lambda_function.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 30
      MemorySize: 256
      Code:
        S3Bucket: !Ref PhotosBucketName
        S3Key: lambda/search-photos.zip
      Environment:
        Variables:
          PHOTOS_BUCKET: !Ref PhotosBucketName

  # ---------------- API Gateway ----------------
  PhotoSearchRestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: photo-search-api

  PhotoSearchRootResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref PhotoSearchRestApi
      ParentId: !GetAtt PhotoSearchRestApi.RootResourceId
      PathPart: photos

  PhotoSearchSearchResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref PhotoSearchRestApi
      ParentId: !GetAtt PhotoSearchRestApi.RootResourceId
      PathPart: search

  PutPhotoMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref PhotoSearchRestApi
      ResourceId: !Ref PhotoSearchRootResource
      HttpMethod: PUT
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub >-
          arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${IndexFunction.Arn}/invocations

  GetSearchMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref PhotoSearchRestApi
      ResourceId: !Ref PhotoSearchSearchResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub >-
          arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SearchFunction.Arn}/invocations

  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - PutPhotoMethod
      - GetSearchMethod
    Properties:
      RestApiId: !Ref PhotoSearchRestApi
      StageName: prod

  # Allow API Gateway to call the Lambdas
  IndexLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref IndexFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${PhotoSearchRestApi}/*/PUT/photos

  SearchLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref SearchFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${PhotoSearchRestApi}/*/GET/search

Outputs:
  FrontendBucketOutput:
    Description: Name of the frontend bucket
    Value: !Ref FrontendBucketName

  PhotosBucketOutput:
    Description: Name of the photos bucket
    Value: !Ref PhotosBucketName

  ApiUrl:
    Description: Invoke URL for the photo search API
    Value: !Sub https://${PhotoSearchRestApi}.execute-api.${AWS::Region}.amazonaws.com/prod

